### ISSUE TITLE
Xcode 13.2.1 import fails at build: `Undefined symbols for architecture x86_64`

### ISSUE THREAD

**Issue by Ontokrat** [OxyDeadbeef/whoami#37]
Hello,
I found a bug at the import in Xcode.
Any idea?

**Describe the bug**
Fail to import the lib in `Xcode 13.2.1`, as part of a backend Rust library used by a `MacOS` app.
`whoami::devicename()` throws:
```
Undefined symbols for architecture x86_64:
  "_SCDynamicStoreCopyComputerName", referenced from:
      whoami::unix::devicename_os::a41b3da222bd09bd0 in redacted.a(whoami-b71e222d3f2cfa22.whoami.25222f57-cgu.0.rcgu.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**To Reproduce**
1. import the crate to a Rust library
2. Export the Rust library  through `cargo build --lib --release --all-targets`
3. Import the `library.a` file in `XCode` (`TARGETS` > `MacOS` > `General` > `Frameworks, Libraries, and Embedded Content`)
4. The build fails with the output code above.

**Expected behavior**
No build failure

**Versions**
- MacOS 12.1
- Xcode 13.2.1
- Rust edition = "2021"
- whoami = "1.2.1"

----
Other template sections not relevant

**Comment by AldaronLau** [comment]
@Ontokrat Thanks for opening this issue.

> Import the library.a file in XCode (TARGETS > MacOS > General > Frameworks, Libraries, and Embedded Content)

I don't see this menu option in XCode (I'm running the same version as you), nor does `cargo build --lib --release --all-targets` produce any .a files, so I wasn't able to reproduce the issue.

-----

Make sure that you have given your XCode app access to the following frameworks required by whoami:

 - `SystemConfiguration`
 - `CoreFoundation`

**Comment by Ontokrat** [comment]
@AldaronLau Thanks for having a look.
You're right, just importing those 2 frameworks in the `swift` file calling the `C` function did the trick. Kudos.
```swift
import CoreFoundation
import SystemConfiguration
```
I didn't see it in the doc, my bad.

Nevertheless, if you're interested by more on the rust library within Xcode:

- the `.a` file is generated in `your_rust_folder > target > release`
- you can see how to import the library in Xcode [here: this article](https://medium.com/visly/rust-on-ios-39f799b3c1dd) gives also more details (use of `cargo-lipo` to generate the library for iOS, but the idea is the same)
