### ISSUE TITLE
Perhaps we should bump our MSRV

### ISSUE THREAD

**Issue by SteveLauC** [OxyDeadbeef/whoami#49]
I am running into this error:

```shell
$ cargo metadata
warning: please specify `--format-version` flag explicitly to avoid compatibility problems
error: failed to download `bumpalo v3.11.1`

Caused by:
  unable to get packages from source

Caused by:
  failed to download replaced source registry `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to parse manifest at `/home/steve/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/bumpalo-3.11.1/Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  supported edition values are `2015` or `2018`, but `2021` is unknown

$ rg "bumpalo"
Cargo.toml
31:[target.'cfg(target_arch = "wasm32")'.dependencies.bumpalo]
```
This is because [`bumpalo` bumps their MSRV to 1.56](https://github.com/fitzgen/bumpalo/pull/179), so perhaps we should also bump our MSRV. 

Since `whoami` [won't bump MSRV until a major version update](https://github.com/ardaku/whoami#msrv), an alternative approach is to use an older version of `bumpalo`.

**Comment by AldaronLau** [comment]
If you run [these commands](https://github.com/ardaku/whoami/blob/stable/.github/workflows/ci.yml#L84-L87) the error goes away.  An alternative would be to remove the [rust-toolchain](https://github.com/ardaku/whoami/blob/stable/rust-toolchain) file (which I think would be fine).

Some context: https://github.com/ardaku/whoami/issues/43

**Comment by SteveLauC** [comment]
Thanks for your help
