### ISSUE TITLE
Use Result enum instead of hardcoding "Unknown" username

### ISSUE THREAD

**Issue by kiilerix** [OxyDeadbeef/whoami#64]
It would be nice to be consistent with the Rust convention of using Result. There *could* be an actual user with the name "Unknown".

Please consider changing that in version 2 ... or provide additional functions with new result types.

**Comment by AldaronLau** [comment]
@kiilerix this is already planned :smile: 

See https://github.com/ardaku/whoami/issues/31 (4th item down)

And https://github.com/ardaku/whoami/issues/30

Exact details of the plan haven't been written down yet, though - so I'll put them here, and use this issue to track completion.

 - Step 1; https://github.com/ardaku/whoami/issues/30
 - Step 2; Add `fallible` module for whoami version 1
 - Step 3; Deprecate? All non-fallible APIs
 - Step 4; For whoami version 2, remove non-fallible APIs and make the `fallible` module the root API

If step 2 is completed (which depends on step 1), I think that should resolve this issue, step 3 and 4 are likely future changes I've been thinking about.

I should really add https://github.com/ardaku/whoami/issues/30 to This Week in Rust's call for participation section...
