### ISSUE TITLE
Expose unmodified hostname (non-lowercase)

### ISSUE THREAD

**Issue by davidkna** [OxyDeadbeef/whoami#82]
**Is your feature request related to a problem? Please describe.**
The hostname is currently being coerced into lowercase, but hostnames on Windows are usually expected to be all-uppercase and on unix systems hostnames aren't guaranteed to be lowercase either (https://github.com/starship/starship/issues/5666).

**Describe the solution you'd like**
Expose an API that returns the unmodified system-provided hostname.

**Describe alternatives you've considered**
Change the API not to modify the system-provided hostname.

**Additional context**
https://github.com/starship/starship/issues/5666
https://github.com/ardaku/whoami/issues/39

**Comment by AldaronLau** [comment]
Thanks for opening this issue @davidkna!

I think the current behavior could be rethought, leaning towards the alternative.  Linking to https://github.com/ardaku/whoami/issues/39, as it's relevant here.  Since hostnames are case-insensitive, I'm guessing the reasoning for keeping the casing here is specifically for UI display, which normally I would defer to devicename rather than hostname for, but the case of a shell is different.  In the case of Windows, though, I'm unclear as to what should be expected; Should it be expected to be all-caps, or should it be expected to match the devicename (camel-case in that issue)?

**Comment by davidkna** [comment]
As far as I know, hostnames are still more relevant for networking than device names, and I feel that for display it's useful to preserve any casing. Windows usually uses all-caps in the user-interface for hostnames, so I'm not sure if doing magic behind the scenes is useful, but if they match, I imagine is unlikely to do any harm.
Also, accoriding to this [serverfault answer](https://serverfault.com/a/752295) case-sensitivity of hostnames is only discouraged, not forbidden in the specifications.

**Comment by AldaronLau** [comment]
> accoriding to this [serverfault answer](https://serverfault.com/a/752295) case-sensitivity of hostnames is only discouraged, not forbidden in the specifications.

Interesting, thanks for bringing this up.

> As far as I know, hostnames are still more relevant for networking than device names, and I feel that for display it's useful to preserve any casing. Windows usually uses all-caps in the user-interface for hostnames, so I'm not sure if doing magic behind the scenes is useful, but if they match, I imagine is unlikely to do any harm.

Thanks, this answers my question, in that using the hostname casing as specified from the windows API WhoAmI would be more accurate to the specification than using the device name casing - (usually?) all caps, especially with the case-sensitivity issue.

Will revert that part of https://github.com/ardaku/whoami/commit/8445e54135db829fe9d51b882fe69c6e87598f16

**Comment by AldaronLau** [comment]
Unmodified hostname is available via [`whoami::fallible::hostname()`](https://docs.rs/whoami/1.5.0-pre.0/whoami/fallible/fn.hostname.html) in the pre-release: https://crates.io/crates/whoami/1.5.0-pre.0

If you'd like to help test, I'd like to know if you run into any issues testing with the pre-releases.  Thanks again, @davidkna!
